import React, { useEffect, useMemo, useState } from 'react';
import { createClient } from '@supabase/supabase-js';
import { Search, MapPin, BedDouble, Bath, Ruler, Heart, Plus, X, ArrowUpRight, ShieldCheck, SlidersHorizontal, Building2, KeyRound, Menu } from 'lucide-react';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = supabaseUrl && supabaseKey && !supabaseUrl.includes('YOUR_PROJECT') ? createClient(supabaseUrl, supabaseKey) : null;
const demo = [
 {id:'d1',title:'فيلا عصرية بإطلالة مميزة',city:'الرياض',district:'حي النرجس',price:2450000,type:'فيلا',purpose:'للبيع',beds:5,baths:4,area:360,image:'https://images.unsplash.com/photo-1600595468467-5e6b2c888bc0?auto=format&fit=crop&w=1000&q=85'},
 {id:'d2',title:'شقة أنيقة قريبة من الخدمات',city:'جدة',district:'حي الشاطئ',price:92000,type:'شقة',purpose:'للإيجار',beds:3,baths:2,area:145,image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85'},
 {id:'d3',title:'تاون هاوس بتصميم راقٍ',city:'الرياض',district:'حي الملقا',price:1780000,type:'تاون هاوس',purpose:'للبيع',beds:4,baths:3,area:280,image:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1000&q=85'},
 {id:'d4',title:'منزل عائلي واسع وحديث',city:'الدمام',district:'حي الشاطئ',price:1350000,type:'فيلا',purpose:'للبيع',beds:4,baths:3,area:310,image:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=85'},
 {id:'d5',title:'شقة مشرقة بتشطيبات فاخرة',city:'مكة',district:'حي العزيزية',price:68000,type:'شقة',purpose:'للإيجار',beds:2,baths:2,area:120,image:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=85'},
 {id:'d6',title:'فيلا مستقلة مع حديقة خاصة',city:'الخبر',district:'حي الحزام الذهبي',price:2200000,type:'فيلا',purpose:'للبيع',beds:5,baths:5,area:400,image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85'}
];
const money = (n) => new Intl.NumberFormat('ar-SA').format(n || 0);
function App(){
 const [listings,setListings]=useState(import.meta.env.PROD?[]:demo),[search,setSearch]=useState(''),[city,setCity]=useState('الكل'),[purpose,setPurpose]=useState('الكل'),[type,setType]=useState('الكل'),[modal,setModal]=useState(false),[form,setForm]=useState({title:'',city:'الرياض',district:'',price:'',type:'فيلا',purpose:'للبيع',beds:'',baths:'',area:'',phone:''}),[imageFile,setImageFile]=useState(null),[notice,setNotice]=useState(''),[saved,setSaved]=useState([]),[mobile,setMobile]=useState(false),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!supabase){if(import.meta.env.PROD)setNotice('الموقع ينتظر إعداد اتصال Supabase.');return}supabase.from('listings').select('*').eq('status','published').order('created_at',{ascending:false}).limit(60).then(({data,error})=>{if(error){setListings([]);setNotice('تعذر تحميل العقارات من قاعدة البيانات.');return}setListings(data||[])});},[]);
 const filtered=useMemo(()=>listings.filter(x=>(city==='الكل'||x.city===city)&&(purpose==='الكل'||x.purpose===purpose)&&(type==='الكل'||x.type===type)&&(`${x.title} ${x.city} ${x.district}`.toLowerCase().includes(search.trim().toLowerCase()))),[listings,city,purpose,type,search]);
 const update=(e)=>setForm({...form,[e.target.name]:e.target.value});
 async function submit(e){e.preventDefault();setNotice('');if(!supabase){setNotice('أضف إعدادات Supabase في ملف .env.local لتفعيل حفظ الإعلانات.');return}setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setNotice('سجّل الدخول أولاً من زر «تسجيل الدخول» حتى تتمكن من نشر إعلانك.');setLoading(false);return}let imageUrl=null;let imagePath=null;if(imageFile){if(imageFile.size>5242880||!['image/jpeg','image/png','image/webp'].includes(imageFile.type)){setNotice('اختر صورة JPG أو PNG أو WebP لا يتجاوز حجمها 5 ميغابايت.');setLoading(false);return}imagePath=`${user.id}/${crypto.randomUUID()}.${imageFile.name.split('.').pop().toLowerCase()}`;const {error:uploadError}=await supabase.storage.from('property-images').upload(imagePath,imageFile,{contentType:imageFile.type,upsert:false});if(uploadError){setNotice('تعذر رفع الصورة. تحقق من إعدادات تخزين Supabase.');setLoading(false);return}imageUrl=supabase.storage.from('property-images').getPublicUrl(imagePath).data.publicUrl}const row={title:form.title.trim(),city:form.city,district:form.district.trim(),price:Number(form.price),type:form.type,purpose:form.purpose,beds:Number(form.beds||0),baths:Number(form.baths||0),area:Number(form.area),image:imageUrl,user_id:user.id,status:'pending'};const {data,error}=await supabase.from('listings').insert(row).select().single();if(error){if(imagePath)await supabase.storage.from('property-images').remove([imagePath]);setLoading(false);setNotice('تعذر حفظ الإعلان. تحقق من مخطط Supabase وسياسات الوصول.');return}const {error:contactError}=await supabase.from('listing_contacts').insert({listing_id:data.id,user_id:user.id,phone:form.phone.trim()});if(contactError){await supabase.from('listings').delete().eq('id',data.id);if(imagePath)await supabase.storage.from('property-images').remove([imagePath]);setLoading(false);setNotice('تعذر حفظ بيانات التواصل؛ لم يتم نشر الإعلان.');return}setLoading(false);setModal(false);setForm({title:'',city:'الرياض',district:'',price:'',type:'فيلا',purpose:'للبيع',beds:'',baths:'',area:'',phone:''});setImageFile(null);setNotice('استلمنا إعلانك وسيظهر بعد المراجعة.');window.scrollTo({top:500,behavior:'smooth'});}
 return <><header className="top"><div className="nav wrap"><a href="#top" className="brand"><span className="brand-mark">د</span><span>دار<small>بيتك يبدأ من هنا</small></span></a><nav className={mobile?'nav-links open':'nav-links'}><a href="#listings" onClick={()=>setMobile(false)}>العقارات</a><a href="#how" onClick={()=>setMobile(false)}>كيف يعمل</a><a href="#about" onClick={()=>setMobile(false)}>عن دار</a></nav><div className="nav-actions"><a className="login" href="#login" onClick={async e=>{e.preventDefault();if(!supabase){setNotice('اربط المشروع بـ Supabase لتفعيل تسجيل الدخول.');return}const email=window.prompt('أدخل بريدك الإلكتروني لإرسال رابط تسجيل الدخول');if(!email)return;const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});setNotice(error?'تعذر إرسال رابط الدخول. تحقق من إعدادات البريد.':'أرسلنا رابط الدخول إلى بريدك الإلكتروني.')}}><KeyRound size={16}/> تسجيل الدخول</a><button className="primary nav-post" onClick={()=>setModal(true)}><Plus size={17}/> أضف عقارك</button><button className="menu" onClick={()=>setMobile(!mobile)} aria-label="القائمة"><Menu/></button></div></div></header>
 <main id="top"><section className="hero"><div className="hero-bg"></div><div className="wrap hero-content"><span className="eyebrow"><span className="live-dot"></span> بيتك أقرب مما تتخيل</span><h1>ابحث عن بيتك،<br/><em>على طريقتك.</em></h1><p>عقارات مختارة من جميع أنحاء المملكة.<br/>اكتشف بيتك القادم أو اعرض عقارك بسهولة.</p><div className="search-box"><div className="search-field"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث بالمدينة أو الحي أو نوع العقار"/></div><select value={city} onChange={e=>setCity(e.target.value)} aria-label="المدينة"><option>الكل</option>{['الرياض','جدة','الدمام','مكة','الخبر'].map(c=><option key={c}>{c}</option>)}</select><button className="primary search-button" onClick={()=>document.getElementById('listings').scrollIntoView({behavior:'smooth'})}><Search size={17}/> ابحث</button></div><div className="trust"><ShieldCheck size={16}/> إعلانات واضحة وتجربة آمنة من البداية</div></div><div className="hero-caption"><span>مجموعة مختارة</span><span>01 / 06</span></div></section>
 <section className="wrap stats"><div><strong>+٢٬٤٠٠</strong><span>عقار معروض</span></div><div><strong>١٢</strong><span>مدينة سعودية</span></div><div><strong>+٨٥٠</strong><span>عملية ناجحة</span></div><div className="stats-note"><span className="live-dot"></span> عقارك القادم ينتظرك</div></section>
 <section className="listing-section wrap" id="listings"><div className="section-head"><div><span className="eyebrow muted">اختيارات تناسبك</span><h2>عقارات تستحق الاكتشاف<span className="accent">.</span></h2><p>تصفّح أحدث العقارات المعروضة في المملكة</p></div><button className="outline" onClick={()=>setModal(true)}><Plus size={17}/> اعرض عقارك</button></div><div className="filter-row"><div className="chips">{['الكل','للبيع','للإيجار'].map(v=><button className={purpose===v?'chip active':'chip'} key={v} onClick={()=>setPurpose(v)}>{v}</button>)}</div><label className="type-filter"><SlidersHorizontal size={16}/><select value={type} onChange={e=>setType(e.target.value)}><option>الكل</option><option>فيلا</option><option>شقة</option><option>تاون هاوس</option><option>أرض</option></select></label></div><div className="cards">{filtered.map((item,i)=><article className="card" key={item.id}><div className="card-image"><img src={item.image||'https://images.unsplash.com/photo-1600595468467-5e6b2c888bc0?auto=format&fit=crop&w=1000&q=85'} alt={item.title} loading="lazy"/><span className="purpose-tag">{item.purpose}</span><button className={saved.includes(item.id)?'save saved':'save'} aria-label="حفظ العقار" onClick={()=>setSaved(saved.includes(item.id)?saved.filter(id=>id!==item.id):[...saved,item.id])}><Heart size={18} fill={saved.includes(item.id)?'currentColor':'none'}/></button><span className="photo-count">0{i+1} / 04</span></div><div className="card-body"><div className="card-place"><MapPin size={14}/>{item.city} · {item.district}</div><h3>{item.title}</h3><div className="features"><span><BedDouble size={16}/>{item.beds||0} غرف</span><span><Bath size={15}/>{item.baths||0} حمام</span><span><Ruler size={15}/>{money(item.area)} م²</span></div><div className="card-bottom"><div><strong>{money(item.price)}</strong><small> ر.س {item.purpose==='للإيجار'?' / سنوي':''}</small></div><button className="arrow" aria-label="تفاصيل العقار"><ArrowUpRight size={18}/></button></div></div></article>)}</div>{filtered.length===0&&<div className="empty">لا توجد عقارات تطابق بحثك حالياً.</div>}</section>
 <section className="promo" id="how"><div className="wrap promo-inner"><div><span className="eyebrow">تملك عقاراً؟</span><h2>الخطوة الأولى<br/>نحو مشتريك القادم.</h2><p>انشر إعلانك مجاناً، وأوصل عقارك إلى آلاف الباحثين عن منزلهم الجديد.</p><button className="light-button" onClick={()=>setModal(true)}>ابدأ بإضافة عقارك <ArrowUpRight size={16}/></button></div><div className="promo-art"><div className="arch"><Building2 size={58} strokeWidth={1}/></div><span className="art-label">مكانك يبدأ هنا</span></div></div></section>
 <section className="wrap steps" id="about"><div><span className="eyebrow muted">بكل بساطة</span><h2>طريقك إلى العقار<br/>أوضح مع دار.</h2></div><div className="step"><span>01</span><h3>ابحث بذكاء</h3><p>فلتر النتائج بالمدينة ونوع العقار لتصل لما يناسبك.</p></div><div className="step"><span>02</span><h3>تواصل مباشرة</h3><p>تفاصيل واضحة تساعدك على اتخاذ الخطوة بثقة.</p></div><div className="step"><span>03</span><h3>اعرض بسهولة</h3><p>أضف عقارك خلال دقائق واجعله مرئياً للمهتمين.</p></div></section></main><footer><div className="wrap foot"><a href="#top" className="brand"><span className="brand-mark">د</span><span>دار<small>بيتك يبدأ من هنا</small></span></a><span>© ٢٠٢٦ دار. جميع الحقوق محفوظة.</span><span className="foot-safe"><ShieldCheck size={15}/> خصوصيتك وأمانك أولويتنا</span></div></footer>
 {notice&&<div className="toast" role="status">{notice}<button onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {modal&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><section className="modal"><div className="modal-head"><div><span className="eyebrow muted">خطوة بسيطة</span><h2>أضف عقارك</h2><p>املأ التفاصيل لإرسال إعلانك للمراجعة.</p></div><button className="close" onClick={()=>setModal(false)} aria-label="إغلاق"><X/></button></div><form onSubmit={submit}><label>عنوان الإعلان<input name="title" required maxLength="120" value={form.title} onChange={update} placeholder="مثال: فيلا عصرية في حي النرجس"/></label><div className="form-grid"><label>المدينة<select name="city" value={form.city} onChange={update}>{['الرياض','جدة','الدمام','مكة','الخبر'].map(c=><option key={c}>{c}</option>)}</select></label><label>الحي<input name="district" required maxLength="80" value={form.district} onChange={update}/></label><label>نوع العقار<select name="type" value={form.type} onChange={update}>{['فيلا','شقة','تاون هاوس','أرض'].map(c=><option key={c}>{c}</option>)}</select></label><label>الغرض<select name="purpose" value={form.purpose} onChange={update}><option>للبيع</option><option>للإيجار</option></select></label><label>السعر (ر.س)<input name="price" type="number" required min="1" value={form.price} onChange={update}/></label><label>المساحة (م²)<input name="area" type="number" required min="1" value={form.area} onChange={update}/></label><label>غرف النوم<input name="beds" type="number" min="0" value={form.beds} onChange={update}/></label><label>الحمامات<input name="baths" type="number" min="0" value={form.baths} onChange={update}/></label></div><label>صورة العقار (اختياري، حتى 5 ميغابايت)<input name="image" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setImageFile(e.target.files?.[0]||null)}/></label><label>رقم التواصل<input name="phone" type="tel" required maxLength="20" value={form.phone} onChange={update} placeholder="05xxxxxxxx"/></label>{notice&&<div className="form-notice">{notice}</div>}<button className="primary submit" disabled={loading}>{loading?'جارٍ الإرسال...':'إرسال للمراجعة'} <ArrowUpRight size={17}/></button><small className="form-privacy"><ShieldCheck size={14}/> رقمك خاص ولا يظهر للزوار.</small></form></section></div>}</>;
}
export default App;

